### ISSUE TITLE
2.0 issue rampdown roadmap

### ISSUE THREAD

**Issue by andrew-boyarshin** [hvanbakel/CsprojToVs2017#154]
* [x] #150 Simplification refactoring
* [x] #150 Property deduplication
* [x] Caching refactoring
* [x] #153 `IncludeItems` refactoring
* [x] #152 `AdditionalPropertyGroups` refactoring (fixed in #157)
* [x] `PackageReferenceTransformation` -> `TestProjectPackageReferenceTransformation`
* [x] #156 Add a better logging solution
* [x] #157 `PropertyGroup`s refactoring
* [x] #160 `PropertyGroups` refactoring (yeah, the 3rd one)
* [x] Verify public API surface class visibility and `sealed` possibility.
* [ ] Rewrite solution file parsing (to fix #161)
* [ ] Publish Release Candidate

**Comment by hvanbakel** [comment]
I don't understand what you mean by the `PackageReferenceTransformation` item?

**Comment by hvanbakel** [comment]
So I would add #156 as `add a better logging solution` to this list

**Comment by andrew-boyarshin** [comment]
@hvanbakel — regarding PackageReferenceTransformation.
The only thing the transformation does is adding MSTest NuGet `PackageReference`s. I suggest renaming the transformation class to indicate that, instead of much more generic name. If additional PackageReference transformations would be required in the future, they l'd better be added as separate transformation.

**Comment by hvanbakel** [comment]
I'll fix that now, and I'll put in a tentative interface for the logging which we can then implement internally.

**Comment by andrew-boyarshin** [comment]
Test file is not renamed. :)

**Comment by hvanbakel** [comment]
I'll do that too, and add a NetFX shim for
https://docs.microsoft.com/en-us/dotnet/api/microsoft.extensions.logging.ilogger?view=aspnetcore-2.1

**Comment by andrew-boyarshin** [comment]
@hvanbakel there's LibLog library too, a different kind of abstraction, but I agree that we can get away with using Microsoft ILogger. We can change Console app later to use Serilog as ILogger backend if we feel like doing it.

**Comment by hvanbakel** [comment]
Exactly, ILogger is a very nice abstraction in my opinion and it's the default abstraction so plenty of implementers out of the box. I'm working on putting that in right now and doing some other refactorings which should put is really close to a 2.0.

**Comment by hvanbakel** [comment]
#156 should now also be addressed, I had to clone the console logger because there's no way to get around the newline for event ids... https://github.com/aspnet/Logging/issues/491

I haven't done a pass on the public API yet, but feedback on the current state would be much appreciated.

**Comment by andrew-boyarshin** [comment]
I am now unable to review the code. Will return in 2 days. I've fetched the latest changes though and will give them a try on a couple of legacy projects.

**Comment by andrew-boyarshin** [comment]
I have found a major issue on 2.0 branch. Will publish a big PR tommorow with that and lots of other fixes.

**Comment by andrew-boyarshin** [comment]
Will send PR in 20 minutes.

**Comment by hvanbakel** [comment]
@andrew-boyarshin just sent you an invite as a collaborator, feel free to do it in a PR though

**Comment by andrew-boyarshin** [comment]
Yeah, I prefer sending PRs even when I have push access. I even admire RPCS3

**Comment by hvanbakel** [comment]
So I applied a few refactorings (see above) and did a pass on the public API and it looks ok to me. That's a really neat improvement over what it was.

@andrew-boyarshin let me know if you see any issues, if not I'll merge this back to master and make that a 2.0 👍

**Comment by hvanbakel** [comment]
per your last comment @andrew-boyarshin, I created a PR 😄

**Comment by andrew-boyarshin** [comment]
Do you intend to release 2.0 or 2.0-rc? There are still minor issues, like empty `PropertyGroup`s and `ItemGroup`s.

**Comment by hvanbakel** [comment]
I just released 2.0-rc1 I don't mind those small issues, those can be addressed later. There was too much good stuff in there too keep the release off. I think we have the API down which is good. Now we're back to:
- Creating PRs against master (I might actually start doing that too)
- We have some open issues but a lot of fixed ones are closed
- We can start doing small increments again and release often

**Comment by hvanbakel** [comment]
Very very very nice work by the way, either you guys are extremely productive or you can (and are willing to) spend a lot of time on this. Absolutely fantastic 🍾

**Comment by hvanbakel** [comment]
@andrew-boyarshin @mungojam anyone has something against creating a 2.0 stable?

**Comment by andrew-boyarshin** [comment]
No, no real issues to prevent that.

**Comment by andrew-boyarshin** [comment]
Unable to do that at the moment, the fix is simple — in `SolutionReader`,
in `if` clause with `continue`, add check for what is returned via `out
string` parameter, if `string.Equals` with folder project type Guid — don't
print warning.

On Aug 24, 2018 12:18 PM, "Mark Adamson" <notifications@github.com> wrote:

I'd like the warnings for solution folders fixed because they will be
confusing for users

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hvanbakel/CsprojToVs2017/issues/154#issuecomment-415653765>,
or mute the thread

**Comment by mungojam** [comment]
I'll have a go at fixing it now, thanks

**Comment by mungojam** [comment]
Happy for release 2 now. The version stripping can be in this or next release, don't mind
